### ISSUE TITLE
#frames isn't corresponds to the experiments in the papers

### ISSUE THREAD

**Issue by ycmin95** [toluwajosh/ubpg#1]
Hi, 

thanks for sharing! I've downloaded the UBPG dataset but found none of the folders corresponds to the experiments in papers.

> A total of 87,156 point cloud frames were collected for training and 29,758 data frames for testing.

> There are 26,712 point cloud frames for training, and 9,802 point cloud frames for testing.

However, none of the training folders has point cloud frames more than 24861, so could you share your point cloud frames list for training and testing?

![QQ图片20190326111748](https://user-images.githubusercontent.com/23148691/54969388-e2d99d80-4fb8-11e9-93a8-0c045d20daaf.png)

**Comment by ycmin95** [comment]
The number of point cloud frames for training performed by subject 1~5 is 87168（train and valid）, and for testing is 28758. 

And the number of training point cloud frames for subject 1 is 24861, and that of testing is 9776, still inconsistent with what is said in papers.

**Comment by toluwajosh** [comment]
Hi @Blueprintf, sorry for the inconsistency in the numbers. I will verify this and give you a feedback. I have also replied your email
